services:
  minio-1:
    image: bitnami/minio
    hostname: minio-1
    volumes:
      - minio1-data:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9010:9001"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.labels.role == minio-1
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopassword
    command: minio server http://minio-1:9000/bitnami/minio/data http://minio-2:9000/bitnami/minio/data http://minio-3:9000/bitnami/minio/data http://minio-4:9000/bitnami/minio/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-2:
    image: bitnami/minio
    hostname: minio-2
    volumes:
      - minio2-data:/bitnami/minio/data
    ports:
      - "9002:9000"
      - "9012:9001"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.labels.role == minio-2
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopassword
    command: minio server http://minio-1:9000/bitnami/minio/data http://minio-2:9000/bitnami/minio/data http://minio-3:9000/bitnami/minio/data http://minio-4:9000/bitnami/minio/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - minio-1

  minio-3:
    image: bitnami/minio
    hostname: minio-3
    volumes:
      - minio3-data:/bitnami/minio/data
    ports:
      - "9003:9000"
      - "9013:9001"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.labels.role == minio-3 
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopassword
    command: minio server http://minio-1:9000/bitnami/minio/data http://minio-2:9000/bitnami/minio/data http://minio-3:9000/bitnami/minio/data http://minio-4:9000/bitnami/minio/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - minio-1
      - minio-2
  minio-4:
    image: bitnami/minio
    hostname: minio-4
    volumes:
      - minio4-data:/bitnami/minio/data
    ports:
      - "9005:9000"
      - "9014:9001"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.labels.role == minio-4
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopassword
    command: minio server http://minio-1:9000/bitnami/minio/data http://minio-2:9000/bitnami/minio/data http://minio-3:9000/bitnami/minio/data http://minio-4:9000/bitnami/minio/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - minio-1
      - minio-2
      - minio-3

networks:
  minio_distributed:
    driver: overlay

volumes:
  minio1-data:
     external: true
  minio2-data:
     external: true
  minio3-data:
     external: true
  minio4-data:
     external: true
